### ISSUE TITLE
Feature request: add UUID functionality to `drives::Device` struct

### ISSUE THREAD

**Issue by bnjmnjrk** [sorcerersr/drives#3]
**Reason**: The UUID can be used to identify a block device independent of its name or mount point.

**Comment by sorcerersr** [comment]
Hi, good idea. I started working on this feature.

**Comment by sorcerersr** [comment]
implemented in v0.6.0 - requires gpt feature to be enabled:
```drives = {  version = "0.6.0",  features = ["gpt"] }```
The GUID of the partition table (gpt) is used as the UUID of the device.
